/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.util.Random;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        Gson json = new Gson();
        Reader reader = new FileReader("recentquotes.json");
        Quotes[] qout = json.fromJson(reader, Quotes[].class);

        Random r = new Random();
        int low = 0;
        int high = qout.length - 1;
        int RandVal = r.nextInt(high - low) + low;
        for (int i = 0; i < qout.length; i++) {
            System.out.println(qout[RandVal]);
            break;
        }

    }
}